set(UGURUGU_CORE_SOURCES
    src/app/ApplicationInstanceLock.cpp
    src/app/ApplicationInstanceLock.hpp
    src/app/Logging.cpp
    src/app/Logging.hpp
    src/app/MemoryBudget.cpp
    src/app/MemoryBudget.hpp
    src/app/RecoveryStore.cpp
    src/app/RecoveryStore.hpp
    src/app/RecoveryWriter.cpp
    src/app/RecoveryWriter.hpp
    src/app/ReleaseNotes.cpp
    src/app/ReleaseNotes.hpp
    src/app/UpdateCheckPolicy.cpp
    src/app/UpdateCheckPolicy.hpp
    src/brush/BrushPreset.cpp
    src/brush/BrushPreset.hpp
    src/brush/EraserPreset.cpp
    src/brush/EraserPreset.hpp
    src/document/Document.cpp
    src/document/Document.hpp
    src/document/DocumentBudget.cpp
    src/document/DocumentBudget.hpp
    src/document/DocumentController.cpp
    src/document/DocumentController.hpp
    src/document/DocumentControllerLayers.cpp
    src/document/DocumentControllerStrokes.cpp
    src/document/DocumentLimits.hpp
    src/document/FrozenFillMask.cpp
    src/document/FrozenFillMask.hpp
    src/document/history/DocumentDelta.cpp
    src/document/history/DocumentDelta.hpp
    src/document/history/DocumentUndoStack.cpp
    src/document/history/HistoryEffects.cpp
    src/document/history/HistoryEffects.hpp
    src/document/history/HistoryMemory.cpp
    src/document/history/HistoryMemory.hpp
    src/document/history/HistoryTypes.hpp
    src/document/history/LogicalHistoryCommand.hpp
    src/document/LayerHierarchy.cpp
    src/document/LayerHierarchy.hpp
    src/document/DocumentOperations.cpp
    src/document/DocumentOperations.hpp
    src/document/SelectionOperation.cpp
    src/document/SelectionOperation.hpp
    src/document/SelectionVisibility.cpp
    src/document/SelectionVisibility.hpp
    src/document/StrokeMask.cpp
    src/document/StrokeMask.hpp
    src/input/StrokeStabilizer.cpp
    src/input/StrokeStabilizer.hpp
    src/io/AnimationExportPolicy.cpp
    src/io/AnimationExportPolicy.hpp
    src/io/DocumentSerializer.cpp
    src/io/DocumentSerializer.hpp
    src/io/SelectionClipboardCodec.cpp
    src/io/SelectionClipboardCodec.hpp
    src/io/WawaV10Reader.cpp
    src/io/WawaV10Reader.hpp
    src/io/WawaV10Importer.cpp
    src/io/WawaV10Importer.hpp
    src/io/serializer/DocumentJsonCodec.cpp
    src/io/serializer/DocumentJsonCodec.hpp
    src/io/serializer/DocumentValidation.cpp
    src/io/serializer/DocumentValidation.hpp
    src/io/serializer/MaskAssetTable.cpp
    src/io/serializer/MaskAssetTable.hpp
    src/io/serializer/PreparedPlanBuilder.cpp
    src/io/serializer/PreparedPlanBuilder.hpp
    src/io/serializer/RasterAssetTable.cpp
    src/io/serializer/RasterAssetTable.hpp
    src/io/serializer/SerializerSchema.hpp
    src/io/ExportWorker.cpp
    src/io/ExportWorker.hpp
    src/io/GifWriter.cpp
    src/io/GifWriter.hpp
    src/io/WebPWriter.cpp
    src/io/WebPWriter.hpp
    src/io/RenderExportPolicy.cpp
    src/io/RenderExportPolicy.hpp
    src/render/BrokenLineModel.cpp
    src/render/BrokenLineModel.hpp
    src/render/ClassicStrokeMotion.cpp
    src/render/ClassicStrokeMotion.hpp
    src/render/DeterministicNoise.cpp
    src/render/DeterministicNoise.hpp
    src/render/FloodFillMask.cpp
    src/render/FloodFillMask.hpp
    src/render/ImageAffineTransformer.cpp
    src/render/ImageAffineTransformer.hpp
    src/render/ImageResampler.cpp
    src/render/ImageResampler.hpp
    src/render/IncrementalStrokeRenderer.cpp
    src/render/IncrementalStrokeRenderer.hpp
    src/render/LayerCompositionPlan.cpp
    src/render/LayerCompositionPlan.hpp
    src/render/MotionTimeModel.cpp
    src/render/MotionTimeModel.hpp
    src/render/engine/DisplayScaleReplay.cpp
    src/render/engine/DisplayScaleReplay.hpp
    src/render/engine/LayerHierarchyCompositor.cpp
    src/render/engine/LayerHierarchyCompositor.hpp
    src/render/engine/LayerOperationReplay.cpp
    src/render/engine/LayerOperationReplay.hpp
    src/render/engine/PreviewScale.cpp
    src/render/engine/PreviewScale.hpp
    src/render/RenderEngine.cpp
    src/render/RenderEngine.hpp
    src/render/RenderEngineStrokes.cpp
    src/render/PreviewMemoryUsage.hpp
    src/render/PreviewRenderPolicy.cpp
    src/render/PreviewRenderPolicy.hpp
    src/render/RasterAssetCache.cpp
    src/render/RasterAssetCache.hpp
    src/render/StrokeCoverageRenderer.cpp
    src/render/StrokeCoverageRenderer.hpp
    src/render/StrokeRenderer.cpp
    src/render/StrokeRenderer.hpp
    src/render/StrokeMotionModel.cpp
    src/render/StrokeMotionModel.hpp
)

set(UGURUGU_UI_SOURCES
    src/ui/BrushPopoverPanel.cpp
    src/ui/BrushPopoverPanel.hpp
    src/ui/BrushPresetButton.cpp
    src/ui/BrushPresetButton.hpp
    src/ui/BrushSizeRow.cpp
    src/ui/BrushSizeRow.hpp
    src/ui/BucketPopoverPanel.cpp
    src/ui/BucketPopoverPanel.hpp
    src/ui/CanvasFrameView.cpp
    src/ui/CanvasFrameView.hpp
    src/ui/CanvasOverlayView.cpp
    src/ui/CanvasOverlayView.hpp
    src/ui/CanvasSizeDialog.cpp
    src/ui/CanvasSizeDialog.hpp
    src/ui/CanvasTypes.hpp
    src/ui/CanvasViewport.cpp
    src/ui/CanvasViewport.hpp
    src/ui/CanvasWidget.cpp
    src/ui/CanvasWidget.hpp
    src/ui/CanvasWidgetEvents.cpp
    src/ui/CanvasWidgetPreview.cpp
    src/ui/CanvasWidgetSelection.cpp
    src/ui/CanvasWidgetTools.cpp
    src/ui/ColorDock.cpp
    src/ui/ColorDock.hpp
    src/ui/ColorHistoryDock.cpp
    src/ui/ColorHistoryDock.hpp
    src/ui/ColorHistoryGrid.cpp
    src/ui/ColorHistoryGrid.hpp
    src/ui/ColorPairSwatch.cpp
    src/ui/ColorPairSwatch.hpp
    src/ui/ColorWheel.cpp
    src/ui/ColorWheel.hpp
    src/ui/ToolDock.cpp
    src/ui/ToolDock.hpp
    src/ui/ElidingCheckBox.cpp
    src/ui/ElidingCheckBox.hpp
    src/ui/ElidingToolButton.cpp
    src/ui/ElidingToolButton.hpp
    src/ui/EraserPopoverPanel.cpp
    src/ui/EraserPopoverPanel.hpp
    src/ui/EraserPresetButton.cpp
    src/ui/EraserPresetButton.hpp
    src/ui/FileOpenEventRouter.cpp
    src/ui/FileOpenEventRouter.hpp
    src/ui/FrameScrubber.cpp
    src/ui/FrameScrubber.hpp
    src/ui/GifExportDialog.cpp
    src/ui/GifExportDialog.hpp
    src/ui/HelpDialog.cpp
    src/ui/HelpDialog.hpp
    src/ui/Icons.cpp
    src/ui/Icons.hpp
    src/ui/ImageSizeDialog.cpp
    src/ui/ImageSizeDialog.hpp
    src/ui/LayerDock.cpp
    src/ui/LayerDock.hpp
    src/ui/LayerItemDelegate.cpp
    src/ui/LayerItemDelegate.hpp
    src/ui/LayerListWidget.cpp
    src/ui/LayerListWidget.hpp
    src/ui/LayerThumbnailRenderer.cpp
    src/ui/LayerThumbnailRenderer.hpp
    src/ui/LassoPopoverPanel.cpp
    src/ui/LassoPopoverPanel.hpp
    src/ui/DrawingToolSettings.cpp
    src/ui/DrawingToolSettings.hpp
    src/ui/MainWindow.cpp
    src/ui/MainWindow.hpp
    src/ui/MainWindowActions.cpp
    src/ui/MainWindowExport.cpp
    src/ui/MainWindowSettings.cpp
    src/ui/PaletteDockAreaManager.cpp
    src/ui/PaletteDockAreaManager.hpp
    src/ui/PaletteDockTitleBar.cpp
    src/ui/PaletteDockTitleBar.hpp
    src/ui/PopoverToolButton.cpp
    src/ui/PopoverToolButton.hpp
    src/ui/PopoverOptionButton.cpp
    src/ui/PopoverOptionButton.hpp
    src/ui/ResponsiveGrid.cpp
    src/ui/ResponsiveGrid.hpp
    src/ui/SelectionActionBar.cpp
    src/ui/SelectionActionBar.hpp
    src/ui/SelectionShapeButton.cpp
    src/ui/SelectionShapeButton.hpp
    src/ui/ShortcutBinding.cpp
    src/ui/ShortcutBinding.hpp
    src/ui/StrokePropertiesDialog.cpp
    src/ui/StrokePropertiesDialog.hpp
    src/ui/StrokeStabilizationRow.cpp
    src/ui/StrokeStabilizationRow.hpp
    src/ui/SettingsDialog.cpp
    src/ui/SettingsDialog.hpp
    src/ui/Theme.cpp
    src/ui/Theme.hpp
    src/ui/TimelineBar.cpp
    src/ui/TimelineBar.hpp
    src/ui/ToolPopover.cpp
    src/ui/ToolPopover.hpp
    src/ui/WobblePlayButton.cpp
    src/ui/WobblePlayButton.hpp
    src/ui/WobbleDock.cpp
    src/ui/WobbleDock.hpp
    src/ui/WobblePopoverPanel.cpp
    src/ui/WobblePopoverPanel.hpp
    src/ui/WobblePreview.cpp
    src/ui/WobblePreview.hpp
    src/ui/WwpPresetCodec.cpp
    src/ui/WwpPresetCodec.hpp
    src/ui/WandPopoverPanel.cpp
    src/ui/WandPopoverPanel.hpp
    src/ui/WandReferenceButton.cpp
    src/ui/WandReferenceButton.hpp
)

set(UGURUGU_TEST_SOURCES
    tests/AppPolicyTests.cpp
    tests/BrushRenderingTests.cpp
    tests/BrokenLineModelTests.cpp
    tests/ClassicStrokeMotionTests.cpp
    tests/DocumentHistoryTests.cpp
    tests/DocumentLifecycleTests.cpp
    tests/DocumentResizeTests.cpp
    tests/DocumentSchemaTests.cpp
    tests/DocumentTests.cpp
    tests/FrozenFillMaskTests.cpp
    tests/GifWriterTests.cpp
    tests/LayerCommandTests.cpp
    tests/LayerCompositionTests.cpp
    tests/LayerSplitPreviewTests.cpp
    tests/LegacyRenderGoldenTests.cpp
    tests/MaskRegressionTests.cpp
    tests/MotionTimeModelTests.cpp
    tests/RasterAssetTableTests.cpp
    tests/ReleaseNotesTests.cpp
    tests/RenderEngineTests.cpp
    tests/SelectionClipboardTests.cpp
    tests/RenderPreviewTests.cpp
    tests/SelectionPreviewTests.cpp
    tests/SerializationBudgetTests.cpp
    tests/StrokeCommandTests.cpp
    tests/StrokeCoverageTests.cpp
    tests/StrokeRenderingTests.cpp
    tests/StrokeStabilizerTests.cpp
    tests/TestMain.cpp
    tests/TestSuites.hpp
    tests/WobbleAnimationTests.cpp
    tests/WawaV10ReaderTests.cpp
    tests/WebPWriterTests.cpp
    tests/UiDrawingToolTests.cpp
    tests/UiSelectionTests.cpp
    tests/UiSessionTests.cpp
    tests/UiShellTests.cpp
    tests/UiViewportTests.cpp
    tests/support/CanvasWidgetTestAccess.hpp
    tests/support/DocumentControllerTestAccess.hpp
    tests/support/DocumentTestHelpers.hpp
    tests/support/DocumentTestSuites.hpp
    tests/support/MainWindowTestAccess.hpp
    tests/support/RenderTestHelpers.hpp
    tests/support/RenderTestSuites.hpp
    tests/support/UiTestHelpers.hpp
    tests/support/UiTestSuites.hpp
)
